### ISSUE TITLE
refactor charts notebook

### ISSUE THREAD

**Issue by ElliottMetzler** [ElliottMetzler/midterm-project-imdb#25]
For the large chunk at the top, lets see if we can refactor the code a bit to make it easier to read and smoother. In particular, in the portion where you read in the data and sort it, I think it would be best practice here to simply use pandas functions. This will avoid looping through the csv line by line to read it in, and should allow us to cut down on the number of datasets we are creating in this script. 

To read in the csv from the data folder, I think we want something along the lines of this:

this_data_frame = pd.read_csv(PATH_TO_RAW_DATA_FILE)

This code will read in the csv and create a dataframe immediately, without you having to manually assign columns or loop through the csv rows.

Then, for each chart, you can just use the same dataframe, sort the values, create the chart, then move on. That way we only have 1 dataframe and are just sorting in different ways for different frames. To sort a dataframe on a column (or multiple):

sorted_data  = unsorted_data.sort_values(["column_1_to_sort","column_2_to_sort"], ascending = (True or False))

So, a cell in the notebook would look like this:

df = df.sort_values(["column_1_to_sort","column_2_to_sort"], ascending = (True or False))
df.plot(<<whatever you need to plot>>)
plt.show()

**Comment by ElliottMetzler** [comment]
@PedroNBRodrigues see the Graphs_1.0.py file for how I refactored that one - I think a similar approach would be great for the notebook

**Comment by PedroNBRodrigues** [comment]
I used the same code from the .py with a few changes to remove saving the plots and unnecessary code as we will only use it to see the plots
